<script type="text/javascript">
//<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    var lastPrice;
//]]>
</script>

<form action="" id="co-payment-form" class="form form-payment-method clear">
    <div class="fieldset">
        <?php echo $this->getChildHtml('methods') ?>
    </div>
</form><!-- close .form-payment-method -->
<div id="payment-buttons-container" class="checkout-continue-button">
    <button type="button" class="button" onclick="payment.save()">
        <span class="text">Continue</span>
    </button>
</div>
<div id="payment-please-wait" class="checkout-wait" style="display:none;">
    <p>Please wait...</p>
</div>
<script type="text/javascript">
//<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
//]]>
</script>
