<form action="" id="co-shipping-form" class="form form-delivery-address clear">
    <div class="fieldset">
    
		<?php if ($this->customerHasAddresses()): ?>
			<div class="field field-select">
                <label for="shipping-address-select" class="field-label">Select an address from your address book or enter a new address.</label>
                <?php echo $this->getAddressesHtmlSelect('shipping') ?>
            </div>
        <?php endif ?>
    
        <div id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
			<input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
            
			<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
                
            <div class="field field-address">
				<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <label for="shipping:street1" class="field-label required">Address</label>
                <input type="text" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                
				<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <input type="text" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                <?php endfor; ?>
			</div>
            
            <div class="field">
                <label for="shipping:city" class="field-label required">City</label>
                <input type="text" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
            </div>
            
            <div class="field field-select">
                <label for="shipping:region_id" class="field-label required">State or province</label>
                <select id="shipping:region_id" name="shipping[region_id]" class="input validate-select" style="display:none;">
                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                //<![CDATA[
                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                //]]>
                </script>
                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" class="input <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
            </div>
            
            <div class="field">
                <label for="shipping:postcode" class="field-label required">Postcode</label>
                <input type="text" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
            </div>
            
            <div class="field field-select">
                <label for="shipping:country_id" class="field-label required">Country</label>
                <?php echo $this->getCountryHtmlSelect('shipping') ?>
            </div>
            
            <div class="field">
                <label for="shipping:telephone" class="field-label required">Telephone number</label>
                <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" class="input <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
            </div>

			<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()){ ?>
                <div class="field">
                    <div class="option">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                        <label for="shipping:save_in_address_book">Save this address</label>
					</div>
				</div>
            <?php } else { ?>
                <input type="hidden" name="shipping[save_in_address_book]" value="1" />
            <?php } ?>
        </div>
    </div>
        
    <div class="field">
        <div class="option">
            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" />
            <label for="shipping:same_as_billing">Use billing address</label>
        </div>
    </div>
    
    <div id="shipping-buttons-container" class="checkout-continue-button">
        <button type="button" class="button" onclick="shipping.save()">
            <span class="text">Continue</span>
        </button>
    </div>
    <div id="shipping-please-wait" class="checkout-wait" style="display:none;">
    	<p>Please wait...</p>
    </div>

</form><!-- close .form-delivery-address -->
<script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>
