<?php echo $this->getChildHtml('footer.pre-footer') ?>
<footer class="grid-panel panel-footer">
    <div class="grid-row">
    	<div class="grid-col bp2-col6 bp4-col6 ie8-col6">
            <?php echo $this->getChildHtml('footer.logo') ?>
        </div><!-- close .grid-col -->
        <div class="grid-col bp1-col8 bp2-col6 bp3-col4 ie8-col6">
            <?php echo $this->getChildHtml('footer.links-company') ?>
        </div><!-- close .grid-col -->
        <div class="grid-col bp1-col8 bp2-col6 bp3-col4 ie8-col6">
            <?php echo $this->getChildHtml('footer.links-help') ?>
        </div><!-- close .grid-col -->
        <div class="grid-col bp1-col8 bp2-col6 bp3-col4 ie8-col6">
            <?php echo $this->getChildHtml('footer.links') ?>
        </div><!-- close .grid-col -->
        <div class="grid-col bp3-col6 bp4-col6 ie8-col6">
            <?php echo $this->getChildHtml('footer.copyright') ?>
        </div><!-- close .grid-col -->
    </div><!-- close .grid-row -->
</footer><!-- close .grid-panel -->
<?php echo $this->getChildHtml('footer.files') ?>


<script>

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),

  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 

  ga('create', 'UA-43864087-1', 'radvalves-n-radiators.com');

  ga('send', 'pageview');

 

</script>

