<header class="grid-panel panel-header" role="header">
	<div class="grid-row">
		<div class="grid-col">
			<div class="grid-col bp1-col12 bp2-col8 ie8-col6">
				<?php echo $this->getChildHtml('header.logo') ?>
			</div><!-- close .grid-col -->
            <div class="grid-col bp1-col12 bp2-col8">
                <?php echo $this->getChildHtml('header.basket') ?>
            </div><!-- close .grid-col -->
            <div class="grid-col bp1-col-24 bp2-col8">
                <?php echo $this->getChildHtml('header.info') ?>
            </div><!-- close .grid-col -->
		</div><!-- close .grid-col -->
    </div><!-- close .grid-row -->
        <?php echo $this->getChildHtml('navbar') ?>
</header><!-- close .grid-panel -->