<div class="module-form module-form-change-password">
    <h1 class="page-title">Change password</h1>
    <form action="<?php echo $action ?>" method="post" id="form-validate" class="form form-change-password">
        <div class="fieldset">
            <div class="field">
                <label for="current_password" class="field-label required">Current password</label>
                <input type="password" class="input required-entry" name="current_password" id="current_password" />
            </div>
            <div class="field">
                <label for="password" class="field-label required">New password</label>
				<input type="password" class="input required-entry validate-password" name="password" id="password" />
            </div>
            <div class="field">
                <label for="confirmation" class="field-label required">Confirm new password</label>
				<input type="password" class="input required-entry validate-cpassword" name="confirmation" id="confirmation" />
            </div>
        </div>
        <div class="form-buttons">
            <button type="submit" class="button">
                <span class="text">Save password</span>
            </button>
        </div>
    </form><!-- close .form-change-password -->
	<script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate');
    //]]>
    </script>
</div><!-- close .module-form -->