<div class="module-edit-account">
	<h1 class="page-title">Edit account details</h1>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" class="form form-edit-account">
        <div class="fieldset">
            <?php echo $this->getBlockHtml('formkey')?>
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            <div class="field">
                <label for="email" class="field-label required">Email address</label>
                <input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" class="input required-entry validate-email" />
            </div>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
				<?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
            <?php endif ?>
            <div class="field field-options">
            	<div class="option">
                    <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" <?php if($this->getCustomer()->getChangePassword() == 1){ ?> checked="checked"<?php } ?> class="checkbox" />
                    <label for="change_password" class="option-label">Change password</label>
            	</div>
            </div>
        </div>
        <div class="fieldset" style="display:none">
            <div class="field">
                <label for="current_password" class="field-label required">Current password</label>
                <input type="password" class="input" name="current_password" id="current_password" />
            </div>
            <div class="field">
                <label for="password" class="field-label required">New password</label>
                <input type="password" class="input validate-password" name="password" id="password" />
            </div>
            <div class="field">
                <label for="confirmation" class="field-label required">Confirm new password</label>
                <input type="password" class="input validate-cpassword" name="confirmation" id="confirmation" />
            </div>
        </div>
        <div class="form-buttons">
            <button type="submit" class="button">
                <span class="text">Save details</span>
            </button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        function setPasswordForm(arg){
            if(arg){
                $('current_password').up(1).show();
                $('current_password').addClassName('required-entry');
                $('password').addClassName('required-entry');
                $('confirmation').addClassName('required-entry');
    
            }else{
                $('current_password').up(1).hide();
                $('current_password').removeClassName('required-entry');
                $('password').removeClassName('required-entry');
                $('confirmation').removeClassName('required-entry');
            }
        }
        <?php if($this->getCustomer()->getChangePassword()): ?>
            setPasswordForm(true);
        <?php endif; ?>
    //]]>
    </script>
</div><!-- close .module-edit-account -->