<div class="module-form module-form-forgot-password">
    <h1 class="page-title">Forgot your password?</h1>
    <p>Please enter your email address below. You will receive a link to reset your password.</p>
    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate" class="form form-forgot-password">
        <div class="fieldset">
            <div class="field">
            	<label for="email_address" class="field-label required">Email address</label>
                <input type="text" name="email" alt="email" id="email_address" class="input required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
            </div>
    	</div>
        <div class="form-buttons">
            <button type="submit" class="button">
                <span class="text">Submit</span>
            </button>
        </div>
    </form><!-- close .form-forgot-password -->
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
    //]]>
    </script>
</div><!-- close .module-form -->