<div class="module-form module-form-reset-password">
    <h1 class="page-title">Reset password</h1>
    <form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate" class="form form-reset-password">
        <div class="fieldset">
            <div class="field">
                <label for="password" class="field-label required">New password</label>
                <input type="password" class="input required-entry validate-password" name="password" id="password" />
            </div>
            <div class="field">
                <label for="confirmation" class="field-label required">Confirm new password</label>
                <input type="password" class="input required-entry validate-cpassword" name="confirmation" id="confirmation" />
            </div>
        </div>
        <div class="form-buttons">
            <button type="submit" class="button">
                <span class="text">Reset password</span>
            </button>
        </div>
    </form><!-- close .form-reset-password -->
    <script type="text/javascript">
    /*<![CDATA[*/
        var dataForm = new VarienForm('form-validate', true);
    /*]]>*/
    </script>
</div><!-- close .module-form -->