<form id="co-billing-form" action="" class="form form-billing-address clear">
    <div class="fieldset">

        <?php if ($this->customerHasAddresses()): ?>
            <div class="field field-select">
                <label for="billing-address-select" class="field-label">Select an address from your address book or enter a new address.</label>
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        <?php endif; ?>
        
        <div id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
			<input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
            
			<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
            
            <?php if(!$this->isCustomerLoggedIn()){ ?>
                <div class="field">
                    <label for="billing:email" class="field-label required">Email address</label>
                    <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" class="input validate-email required-entry" />
                </div>
            <?php } ?>
            
            <div class="field field-address">
				<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <label for="billing:street1" class="field-label required">Address</label>
                <input type="text" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input <?php echo $_streetValidationClass ?>" />
                
				<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <input type="text" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input <?php echo $_streetValidationClass ?>" />
                <?php endfor; ?>
			</div>

            <div class="field">
                <label for="billing:city" class="field-label required">City</label>
                <input type="text" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" />
            </div>
                            
            <div class="field field-select">
                <label for="billing:region_id" class="field-label required">State or province</label>
                <select id="billing:region_id" name="billing[region_id]" class="input validate-select" style="display:none;">
                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                //<![CDATA[
                    $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                //]]>
                </script>
                <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" class="input <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
            </div>
    
            <div class="field">
                <label for="billing:postcode" class="field-label required">Postcode</label>
                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
            </div>
            
            <div class="field field-select">
                <label for="billing:country_id" class="field-label required">Country</label>
                <?php echo $this->getCountryHtmlSelect('billing') ?>
            </div>
    
            <div class="field">
                <label for="billing:telephone" class="field-label required">Telephone number</label>
                <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" class="input <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
            </div>
    
            <?php if(!$this->isCustomerLoggedIn()){ ?>
                <div id="register-customer-password">
                    <div class="field">
                        <label for="billing:customer_password" class="field-label required">Password</label>
                        <input type="password" name="billing[customer_password]" id="billing:customer_password" class="input required-entry validate-password" />
                    </div>
                    <div class="field">
                        <label for="billing:confirm_password" class="field-label required">Confirm password</label>
                        <input type="password" name="billing[confirm_password]" id="billing:confirm_password" class="input required-entry validate-cpassword" />
                    </div>
                </div>
            <?php } ?>
                        
            <?php if($this->isCustomerLoggedIn() && $this->customerHasAddresses()){ ?>
                <div class="field">
                    <div class="option">
                        <input type="checkbox" name="billing[save_in_address_book]" value="1" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                        <label for="billing:save_in_address_book">Save this address</label>
                    </div>
                </div>
            <?php } else { ?>
                <input type="hidden" name="billing[save_in_address_book]" value="1" />
            <?php } ?>
        </div>
	</div>
             
	<?php if($this->canShip()){ ?>
        <div class="field">
            <div class="option">
                <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" <?php if ($this->isUseBillingAddressForShipping()){ ?>checked="checked"<?php } ?> onclick="$('shipping:same_as_billing').checked = true;" class="radio" />
                <label for="billing:use_for_shipping_yes">Deliver to this address</label>
            </div>
            <div class="option">
                <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0" <?php if (!$this->isUseBillingAddressForShipping()) {?>checked="checked"<?php } ?> onclick="$('shipping:same_as_billing').checked = false;" class="radio" />
                <label for="billing:use_for_shipping_no">Deliver to another address</label>
            </div>
        </div>
    <?php } else { ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php } ?>
    
    <div id="billing-buttons-container" class="checkout-continue-button">
        <button type="button" class="button" onclick="billing.save()">
            <span class="text">Continue</span>
        </button>
    </div>
    <div id="billing-please-wait" class="checkout-wait" style="display:none;">
    	<p>Please wait...</p>
    </div>
    
</form><!-- close .form-billing-address -->
<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function(event) {
            var billingRememberMe = $('co-billing-form').select('#remember-me-box');
            if (billingRememberMe.length > 0) {
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe[0].hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe[0].show();
                }
            }
        });
    }
//]]>
</script>
