<div class="module-masthead-carousel">
	<input type="radio" name="carousel" id="slide1" class="carousel-control" checked />
    <input type="radio" name="carousel" id="slide2" class="carousel-control" disabled="disabled" />
    <input type="radio" name="carousel" id="slide3" class="carousel-control" disabled="disabled" />
    <!-- end carousel controls -->
    <div class="carousel-slides-window">
    	<div class="carousel-slides-mask">
            <ul class="carousel-slides">
                <li class="carousel-slide slide1">
                	<div class="carousel-slide-inner">
                    	<div class="grid-row">
                        	<div class="grid-col bp1-col12">
                                <h2 class="carousel-header">Promotion</h2>
                                <p class="carousel-blurb">Luxury double panel</p>
                                <a class="carousel-link" href="<?php echo $this->getUrl('') ?>offers">View offer<i class="icon-caret-right icon-alt"></i></a>
                            </div><!-- close .grid-col -->
                            <div class="grid-col bp1-col12">
                            	<img class="carousel-img" src=<?php echo $this->getSkinUrl('img/special-offers/luxury-double-panel.jpg')?> />
                            </div><!-- close .grid-col -->
                        </div><!-- close .grid-row -->
                    </div><!-- close .carousel-slide-inner -->
              	</li>
                <li class="carousel-slide slide2">
                	<div class="carousel-slide-inner">
                    	<div class="grid-row">
                        	<div class="grid-col bp3-col12">
                                <h2 class="carousel-header">Promotion 2</h2>
                                <p class="carousel-blurb">100% off everything</p>
                                <a class="carousel-link" href="#">View range<i class="icon-caret-right icon-alt"></i></a>
                            </div><!-- close .grid-col -->
                            <div class="grid-col bp3-col12">
                            	<img class="carousel-img" src="http://placehold.it/180x120" />
                            </div><!-- close .grid-col -->
                        </div><!-- close .grid-row -->
                    </div><!-- close .carousel-slide-inner -->
              	</li>
                <li class="carousel-slide slide3">
                	<div class="carousel-slide-inner">
                    	<div class="grid-row">
                        	<div class="grid-col bp3-col12">
                                <h2 class="carousel-header">Promotion 3</h2>
                                <p class="carousel-blurb">3% off selected products</p>
                                <a class="carousel-link" href="#">View range<i class="icon-caret-right icon-alt"></i></a>
                            </div><!-- close .grid-col -->
                            <div class="grid-col bp3-col12">
                            	<img class="carousel-img" src="http://placehold.it/180x120" />
                            </div><!-- close .grid-col -->
                        </div><!-- close .grid-row -->
                    </div><!-- close .carousel-slide-inner -->
                </li>
            </ul><!-- close .carousel-slides -->
        </div><!-- close .carousel-slides-mask -->
    </div><!-- close .carousel-slides-window -->
    <ul class="carousel-arrows">
        <li><label class="carousel-arrow" for="slide1"><span>Slide 1</span></label></li>
        <!--<li><label class="carousel-arrow" for="slide2"><span>Slide 2</span></label></li>
        <li><label class="carousel-arrow" for="slide3"><span>Slide 3</span></label></li>-->
    </ul><!-- close .carousel-arrows -->    
</div><!-- close .module-masthead-carousel -->