<div class="grid-panel panel-home-masthead">
	<div class="grid-row grid-offset">
        <div class="grid-col bp3-col12">
            <?php echo $this->getChildHtml('masthead.text') ?>
        </div><!-- close .grid-col -->
       	<div class="grid-col bp3-col12 bp3-pull-right">
          	<?php echo $this->getChildHtml('masthead.promo') ?>
       	</div><!-- close .grid-col -->
    </div><!-- close .grid-row -->
</div><!-- close .grid-panel -->