<?php $_shippingRateGroups = $this->getShippingRates(); ?>
<?php if ($_shippingRateGroups){ ?>
    <ul class="delivery-methods-list">
		<?php $shippingCodePrice = array(); ?>
        <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
            <li>
                <span class="delivery-method-name"><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></span>
                <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                    <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
    
                    <?php if ($_rate->getErrorMessage()){ ?>
                        <p><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></p>
                    <?php } else { ?>
                        <div class="field">
                            <div class="option">
                                <?php if ($_sole){ ?>
                                    <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" />
                                <?php } else { ?>
                                    <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>
                                    <?php if ($_rate->getCode() === $this->getAddressShippingMethod()){ ?>
                                        <script type="text/javascript">
                                            //<![CDATA[
                                                lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                                            //]]>
                                        </script>
                                    <?php } ?>
                                <?php } ?>
                                <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                    <?php echo $_excl; ?>
                                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl){ ?>
                                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                    <?php } ?>
                                </label>
                            </div>
                        </div>
                    <?php } ?>
                <?php endforeach; ?>
            </li>
        <?php endforeach; ?>
    </ul>
	<script type="text/javascript">
    //<![CDATA[
        <?php if (!empty($shippingCodePrice)): ?>
            var shippingCodePrice = {<?php echo implode(',',$shippingCodePrice); ?>};
        <?php endif; ?>
        $$('input[type="radio"][name="shipping_method"]').each(function(el){
            Event.observe(el, 'click', function(){
                if (el.checked == true) {
                    var getShippingCode = el.getValue();
                    <?php if (!empty($shippingCodePrice)): ?>
                        var newPrice = shippingCodePrice[getShippingCode];
                        if (!lastPrice) {
                            lastPrice = newPrice;
                            quoteBaseGrandTotal += newPrice;
                        }
                        if (newPrice != lastPrice) {
                            quoteBaseGrandTotal += (newPrice-lastPrice);
                            lastPrice = newPrice;
                        }
                    <?php endif; ?>
                    checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
                    return false;
                }
           });
        });
    //]]>
    </script>
<?php } else { ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php } ?>
