<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('hello') // introduction ?>
<?php echo $this->getChildHtml('info') // account details and newsletter ?>
<?php echo $this->getChildHtml('address') // default addresses ?>
<?php echo $this->getChildHtml('top') // recent orders ?>
<?php echo $this->getChildHtml('info1') // recent reviews ?>
<?php echo $this->getChildHtml('info2') // tags ?>