<div class="field">
	<label for="<?php echo $this->getFieldId('taxvat')?>" class="field-label<?php if ($this->isRequired()){ ?> required<?php } ?>">Tax or VAT number</label>
    <input type="text" id="<?php echo $this->getFieldId('taxvat')?>" name="<?php echo $this->getFieldName('taxvat')?>" value="<?php echo $this->escapeHtml($this->getTaxvat()) ?>" class="input <?php echo $this->helper('customer/address')->getAttributeValidationClass('taxvat') ?>" <?php echo $this->getFieldParams() ?> />
</div>
