<div class="module-email-signup">
    <h2 class="heading">Offers newsletter</h2>
    <p>Subscribe to our newsletter to receive email updates.</p>
    <form class="form form-email-signup" role="form" action="http://radvalves-n-radiators.com/newsletter/subscriber/new/" method="post">
        <div class="fieldset">
            <div class="field">
                <label for="email" class="field-label required">Enter your email address</label>
                <input type="email" name="email" class="input required" placeholder="Email address" />
            </div>
        </div>
        <div class="form-buttons">
            <button type="submit" class="button-icon">
                <span class="hide-text">Sign up</span>
                <i class="icon-caret-right icon-alt"></i>
            </button>
        </div>
    </form><!-- close .form-email-signup -->
</div><!-- close .module-email-signup -->