<div class="module-social-icons">
    <h2 class="heading">Follow us</h2>
    <ul class="social-icons clear">
        <li><a href="#" class="icon-tw">Twitter</a></li>
        <li><a href="#" class="icon-fb">Facebook</a></li>
        <li><a href="#" class="icon-gg">Google+</a></li>
        <li><a href="#" class="icon-pn">Pinterest</a></li>
        <li><a href="#" class="icon-li">LinkedIn</a></li>
    </ul><!-- close .social-icons -->
</div><!-- close .module-social-icons -->