<?php
/**
* VARIABLES
*/
$_store_ID						= Mage::app()->getStore()->getId();
$_product						= $this->getProduct();
$_product_ID 					= $_product->getId();
$_product_url					= $_product->getProductUrl();
$_product_edit_url				= $_product->getConfigureUrl();
$_product_type					= $_product->getTypeId();
$_product_name					= $_product->getName();
$_product_short_description		= $_product->getShortDescription();
$_product_description			= $_product->getDescription();
$_product_image					= $this->helper('catalog/image')->init($_product,'thumbnail')->resize(420,280);
$_product_image_url				= Mage::getModel('catalog/product_media_config')->getMediaUrl($_product->getImage());
$_now							= date("Y-m-d H:m:s");
$_product_new_from_date			= $_product->getNewsFromDate();
$_product_new_to_date			= $_product->getNewsToDate();
$_product_regular_price			= $this->helper('core')->currency($_product->getPrice(),true,false);
$_product_final_price			= $this->helper('core')->currency($_product->getFinalPrice(),true,false);
$_product_rating				= Mage::getModel('review/review_summary')->setStoreId($_store_ID)->load($_product_ID)->getRatingSummary();
$_product_star_rating			= round($_product_rating / 20,1);
?>

<div class="product-summary">
    <h1 class="page-title"><?php echo $_product_name; ?></h1>
	<?php if($_product_type !== 'grouped'){ ?>
        <div class="product-price">
            <?php if($_product_type == 'configurable' || $_product_type == 'bundle'){ ?><span class="from">From</span><?php } ?>
            <?php if($_product_final_price == $_product_regular_price){ ?>
                <span class="price"><?php echo $_product_final_price; ?></span>
            <?php } else { ?>
                <span class="price-old"><?php echo $_product_regular_price; ?></span>
                <span class="price-new"><?php echo $_product_final_price; ?></span>
            <?php } ?>
        </div>
	<?php } ?>
</div><!-- close .product-summary -->
