<div class="module-product-review-form" id="product-review-form">
    <h2 class="heading">Review this product</h2>
	<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
		<?php if($this->getAllowWriteReviewFlag()){ ?>
            <form action="<?php echo $this->getAction() ?>" method="post" class="form form-product-review" id="review-form">
                <div class="fieldset">
                    <div class="field">
                        <label for="nickname_field" class="field-label required">Your name</label>
                        <input type="text" name="nickname" id="nickname_field" class="input required-entry" value="<?php echo $this->htmlEscape($data->getNickname()) ?>" />
                    </div>
                    <div class="field">
                        <label for="summary_field" class="field-label required">Please enter a title for your review</label>
                        <input type="text" name="title" id="summary_field" class="input required-entry" value="<?php echo $this->htmlEscape($data->getTitle()) ?>" />
                    </div>
                    <div class="field field-textarea">
                        <label for="review_field" class="field-label required">Write your review here</label>
                        <textarea name="detail" id="review_field" class="input required-entry"><?php echo $this->htmlEscape($data->getDetail()) ?></textarea>
                    </div>
					<?php if( $this->getRatings() && $this->getRatings()->getSize()){ ?>
                        <div class="field field-rating">
                            <label for="ratings" class="field-label">How would you rate this product?</label>
                                <ul id="product-review-table">
                                    <?php foreach ($this->getRatings() as $_rating): $i++; ?>
                                        <li>
											<?php $i = 0; foreach($_rating->getOptions() as $_option): $i++; ?>
                                                <input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" />
                                            <?php endforeach; ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                        </div>
                    <?php } ?>
                </div>
				<div class="form-buttons">
                    <button type="submit" class="button">
                        <span class="text">Post review</span>
                    </button>
                </div>
                <p>Your review will not appear on our website until it has been approved by an administrator.</p>
            </form><!-- close .form-product-review -->
            <script type="text/javascript">
            //<![CDATA[
                var dataForm = new VarienForm('review-form');
                Validation.addAllThese(
                [
                       ['validate-rating', '<?php echo $this->__('Please select one of each of the ratings above') ?>', function(v) {
                            var trs = $('product-review-table').select('tr');
                            var inputs;
                            var error = 1;
            
                            for( var j=0; j < trs.length; j++ ) {
                                var tr = trs[j];
                                if( j > 0 ) {
                                    inputs = tr.select('input');
            
                                    for( i in inputs ) {
                                        if( inputs[i].checked == true ) {
                                            error = 0;
                                        }
                                    }
            
                                    if( error == 1 ) {
                                        return false;
                                    } else {
                                        error = 1;
                                    }
                                }
                            }
                            return true;
                        }]
                ]
                );
            //]]>
            </script>
        <?php } ?>
    <?php } else { ?>
		<p>Please <a href="<?php echo Mage::helper('customer')->getRegisterUrl(); ?>">register</a> or <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>">sign in</a> to review this product.</p>
    <?php } ?>
</div><!-- close .module-product-review-form -->
