<?php $_option = $this->getOption(); ?>
<div class="field field-note">
	<label class="field-label<?php if($_option->getIsRequire()){ ?> required<?php } ?>"><?php echo $this->htmlEscape($_option->getTitle()) ?></label>
    <?php echo $this->getFormatedPrice() ?></dt>
    <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_FIELD){ ?>
        <input type="text" onchange="opConfig.reloadPrice()" id="options_<?php echo $_option->getId() ?>_text" class="input<?php echo $_option->getIsRequire() ? ' required-entry' : '' ?> <?php echo $_option->getMaxCharacters() ? ' validate-length maximum-length-'.$_option->getMaxCharacters() : '' ?> product-custom-option" name="options[<?php echo $_option->getId() ?>]" value="<?php echo $this->escapeHtml($this->getDefaultValue()) ?>" />
    <?php } elseif ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_AREA){ ?>
        <textarea id="options_<?php echo $_option->getId() ?>_text" onchange="opConfig.reloadPrice()" class="input <?php echo $_option->getIsRequire() ? ' required-entry' : '' ?> <?php echo $_option->getMaxCharacters() ? ' validate-length maximum-length-'.$_option->getMaxCharacters() : '' ?> product-custom-option" name="options[<?php echo $_option->getId() ?>]"><?php echo $this->escapeHtml($this->getDefaultValue()) ?></textarea>
    <?php } ?>
</div>
<?php if ($_option->getMaxCharacters()): ?>
	<p class="note">Your message must be no longer than <?php echo $_option->getMaxCharacters() ?> characters.</p>
<?php endif; ?>

