<div class="module-topbar-secure">
	<!--<p class="topbar-secure-msg">Secure shopping</p>
    <img class="topbar-secure-logo" src="<?php echo $this->getSkinUrl('assets/sprite-cc-icons.png') ?>" alt="Visa, Mastercard, Maestro, Solo, Cirrus" />-->
    <p class="testing-message" style="color:red;">Website currently in testing. Any order places will not be honoured</p>
</div><!-- close .module-topbar-secure -->