<?php
/**
* VARIABLES
*/
$_store_ID						= Mage::app()->getStore()->getId();
$_product						= $this->getProduct();
$_product_ID 					= $_product->getId();
$_product_url					= $_product->getProductUrl();
$_product_edit_url				= $_product->getConfigureUrl();
$_product_type					= $_product->getTypeId();
$_product_name					= $_product->getName();
$_product_short_description		= $_product->getShortDescription();
$_product_description			= $_product->getDescription();
$_product_image					= $this->helper('catalog/image')->init($_product,'thumbnail')->resize(420,280);
$_product_image_url				= Mage::getModel('catalog/product_media_config')->getMediaUrl($_product->getImage());
$_now							= date("Y-m-d H:m:s");
$_product_new_from_date			= $_product->getNewsFromDate();
$_product_new_to_date			= $_product->getNewsToDate();
$_product_regular_price			= $this->helper('core')->currency($_product->getPrice(),true,false);
$_product_final_price			= $this->helper('core')->currency($_product->getFinalPrice(),true,false);
$_product_rating				= Mage::getModel('review/review_summary')->setStoreId($_store_ID)->load($_product_ID)->getRatingSummary();
$_product_star_rating			= round($_product_rating / 20,1);
?>

<div class="product-gallery">
	<?php if($_product_new_from_date < $_now && $_product_new_to_date > $_now){ ?><span class="product-icon-new">New!</span><?php } ?>
    <div class="product-image">
        <img src="<?php echo $_product_image; ?>" alt="<?php echo $_product_name; ?>" />
    </div>
    <div class="product-image-thumbs clear">
    	<ul>
		<?php foreach ($this->getGalleryImages() as $_image): ?>
        <?php $_label = $this->htmlEscape($_image->getLabel()); ?>
        <?php if (strpos($_label, 'technical drawing') ==false) { ?>
        	<li class="image-thumb">
                <a data-lightbox="lightbox" class="lightbox-link" href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>">
                	<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(50,50); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                </a>
            </li>
      	<?php } else { ?>
			<li>
            	<a data-lightbox="lightbox" class="technical-drawing-link" href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>">View technical drawing</a>
                <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>" class="technical-drawing-download" title="Download technical drawing" download="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><i class="icon-download-alt"></i><span>Download technical drawing</span></a>
            </li>		
		<?php } endforeach; ?>
    	</ul>
  	</div>
</div><!-- close .product-gallery -->