<div class="module-contact-details module-pre-footer-contact-details">
    <h2 class="heading-alt-large">Contact us</h2>
    <ul class="contact-details">
    	<li>
            <a href="tel:+441619281220" class="detail tel">
                <i class="icon-phone-sign"></i>
                <span class="detail-short">Call us</span>
                <span class="detail-full">+44 (0)161 928 1220</span>
            </a>
        </li>
        <li>
            <a href="mailto:info@radvalves-n-radiators.com" class="detail email">
            	<i class="icon-envelope-alt"></i>
                <span class="detail-short">Email us</span>
                <span class="detail-full">info@radvalves-n-radiators.com</span>
            </a>
        </li>
        <li>
            <p class="detail address clear">
                <i class="icon-map-marker"></i>
           		<span>Unit 1B, Stag Industrial Estate, Atlantic Street, Broadheath, Altrincham, Cheshire, WA14 5DW<br />
                <a href="https://www.google.co.uk/maps/preview#!q=Unit+1B%2C+Stag+Industrial+Estate+Atlantic+Street+Broadheath+Altrincham++Cheshire+WA14+5DW&data=!4m10!1m9!4m8!1m3!1d4040394!2d-4.064941!3d53.800651!3m2!1i1366!2i643!4f13.1">View on Google Maps</a></span></p>
        </li>
	</ul><!-- close .contact-details -->
</div><!-- close .module-contact-details -->