<div class="grid-panel panel-pre-footer">
	<div class="grid-row">
    	<div class="grid-col bp3-col8 pre-footer-col">
    		<?php echo $this->getChildHtml('footer.contract-quotes') ?>
    	</div><!-- close .grid-col -->
        <div class="grid-col bp3-col8 pre-footer-col">
    		<?php echo $this->getChildHtml('footer.news') ?>
    	</div><!-- close .grid-col -->
        <div class="grid-col bp3-col8 pre-footer-col">
    		<?php echo $this->getChildHtml('footer.contact-details') ?>
    	</div><!-- close .grid-col -->
   	</div><!-- close .grid-row -->
</div><!-- close .panel-pre-footer -->