<div class="module-offer-news module-pre-footer-offer-news">
    <h2 class="heading-alt-large">Special offer news</h2>
    <p>Sign up to our new e-newsletter to receive product news and great offers &amp; promotions.</p>
    <form class="form" role="form" action="http://radvalves-n-radiators.com/newsletter/subscriber/new/" method="post">
                <input type="text" placeholder="Email address" class="field">
                <button type="submit" class="button form-button">Sign up</button>
	</form>
</div><!-- close .module-offer-news -->