<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>

<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>

<ol class="opc" id="opcheckout">

<?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>

<?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>

    <li id="opc-<?php echo $_stepId ?>" class="step <?php echo $_stepId ?> section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">

        <a href="#" class="tab step<?php echo $i ?>"><h2>

		

			<?php if ($_stepInfo['label'] == 'Checkout Method') { ?>Begin secure checkout<?php } ?>

			<?php if ($_stepInfo['label'] == 'Billing Information') { ?>Billing address<?php } ?>

			<?php if ($_stepInfo['label'] == 'Shipping Information') { ?>Delivery address<?php } ?>

			<?php if ($_stepInfo['label'] == 'Shipping Method') { ?>Delivery method<?php } ?>

			<?php if ($_stepInfo['label'] == 'Payment Information') { ?>Payment method<?php } ?>

			<?php if ($_stepInfo['label'] == 'Order Review') { ?>Review your order<?php } ?>

        

        </h2></a>

        <div class="inner a-item" style="display:none;">

            <?php echo $this->getChildHtml($_stepId) ?>

        </div>

    </li>

<?php endforeach ?>

</ol>



<script type="text/javascript">

//<![CDATA[

    var accordion = new Accordion('opcheckout', 'a.tab', true);

    <?php if($this->getActiveStep()): ?>

    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');

    <?php endif ?>

    var checkout = new Checkout(accordion,{

        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',

        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',

        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',

        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}

    );

//]]>

</script>

