<?php $_code=$this->getMethodCode() ?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">
    <div class="field">
        <label for="<?php echo $_code ?>_cc_owner" class="required">Name on card</label>
        <input type="text" class="input required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
    </div>
    <div class="field field-select">
        <label for="<?php echo $_code ?>_cc_type" class="field-label required">Card type</label>
        <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
            <option value="">Please select</option>
			<?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
        </select>
    </div>

    <div class="field">
    	<label for="<?php echo $_code ?>_cc_number" class="field-label required">Credit card number</label>
        <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" class="input validate-cc-number validate-cc-type" value="" />
	</div>

    <div class="field field-select card-date clear">
        <label for="<?php echo $_code ?>_expiration" class="field-label required">Card expiration date</label>
        <div class="field-month">
            <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
            </select>
        </div>
        <div class="field-year">
			<?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    
    <?php echo $this->getChildHtml() ?>
    
    <?php if($this->hasVerification()){ ?>
        <div class="field field-cvv">
            <label for="<?php echo $_code ?>_cc_cid" class="field-label required">Card verification number</label>
            <p class="note">This is the three-digit number on the back of your card</p>
            <input type="text" class="input cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
        </div>
    <?php } ?>
    
    <?php if ($this->hasSsCardType()){ ?>
    <div id="<?php echo $_code ?>_cc_type_ss_div">
        <div class="field">
        	<label for="<?php echo $_code ?>_cc_issue">Issue number</label>
            <input type="text" class="input validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
		</div>
        <div class="field field-select card-date clear">
            <label for="<?php echo $_code ?>_start_month">Start date</label>
            <div class="field-month">
                <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="field-year">
                <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
					<?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
		</div>
        <script type="text/javascript">
        //<![CDATA[
        var SSChecked<?php echo $_code ?> = function() {
            var elm = $('<?php echo $_code ?>_cc_type');
            if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                $('<?php echo $_code ?>_cc_type_ss_div').show();
            } else {
                $('<?php echo $_code ?>_cc_type_ss_div').hide();
            }
        };

        Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
        SSChecked<?php echo $_code ?>();
        //]]>
        </script>
    </div>
    <?php } ?>
</div>
